name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.6'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip==23.1.2
          pip install numpy==2.2.1
          python -m pip install hyperon==0.2.5
          metta --version

      - name: Run tests
        run: |
          python3 run-tests.py